import type { Project } from "@/types/project";

export const projectTypes = [
  "All",
  "Full Stack",
  "Next.js",
  "React.js",
  "JavaScript",
  "AI/ML",
] as const;

export type ProjectType = (typeof projectTypes)[number];

export const projectsFallback: Project[] = [
  {
    id: 1,
    userId: null,
    title: "NexCart",
    subtitle: "Modern E-commerce Platform",
    type: "Next.js",
    description:
      "A modern, full-featured e-commerce platform built with Next.js, TypeScript, and the MERN stack. NexCart delivers a seamless shopping experience with role-based dashboards, product management, secure authentication, and scalable architecture.",
    images: [
      "https://i.postimg.cc/zGq9WXwK/Screenshot-2026-03-29-at-3-45-05-PM.png",
    ],
    features: [
      "User authentication and authorization",
      "Role-based access control (Admin/User)",
      "Product listing and management",
      "Shopping cart and checkout system",
      "Order management",
      "Responsive and modern UI",
      "Secure API integration",
      "Performance optimized with SSR",
    ],
    techStack: [
      "Next.js",
      "TypeScript",
      "MongoDB",
      "Express.js",
      "Node.js",
      "Tailwind CSS",
    ],
    tags: ["@nextjs", "@typescript", "@mongodb", "@express", "@nodejs"],
    links: {
      frontend: "https://github.com/Samin1362/NexCart-Frontend.git",
      backend: "https://github.com/Samin1362/NexCart-Backend.git",
      live: "https://nex-cart-frontend.vercel.app",
    },
    credentials: { note: "Demo credentials are available on the login page" },
    borderColor: "#6366F1",
    gradient: "linear-gradient(180deg, #6366F1, #000)",
    displayOrder: 0,
    isVisible: true,
  },
  {
    id: 2,
    userId: null,
    title: "Coaching Management System",
    subtitle: "Full Stack Project",
    type: "Full Stack",
    description:
      "A comprehensive coaching management system built with the MERN stack. This platform streamlines administrative tasks, student management, and educational workflows for coaching institutes. Features include student enrollment, attendance tracking, payment processing, and real-time notifications.",
    images: [
      "https://i.postimg.cc/3rPBPzQ3/Screenshot-2026-01-10-at-9-04-43-PM.png",
    ],
    features: [
      "User authentication and authorization",
      "Role-based access control (Admin/Teacher/Student)",
      "Student enrollment and management",
      "Attendance tracking system",
      "Payment processing integration",
      "Real-time notifications",
      "Performance analytics dashboard",
    ],
    techStack: ["React", "MongoDB", "Express.js", "Node.js", "Firebase"],
    tags: ["@react", "@mongodb", "@express", "@nodejs"],
    links: {
      frontend:
        "https://github.com/Samin1362/Rootx_Coaching_Management_System_Client_Side.git",
      backend:
        "https://github.com/Samin1362/Rootx_Coaching_Management_System_Server_Side.git",
      live: "https://rootx-cms-firebase-project.web.app/",
    },
    credentials: {
      email: "samin@gmail.com",
      password: "1234samin",
      note: "Admin account for testing",
    },
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #FFD580, #000)",
    displayOrder: 1,
    isVisible: true,
  },
  {
    id: 3,
    userId: null,
    title: "Scholarship Management Platform",
    subtitle: "Full Stack Project",
    type: "Full Stack",
    description:
      "ScholarStream is a full-featured scholarship discovery and application platform that connects students with global scholarship opportunities. It simplifies the application process, enables secure payments, provides real-time tracking, and offers analytics and role-based management for students, moderators, and administrators.",
    images: [
      "https://i.postimg.cc/wvG5v5Hh/Screenshot-2026-02-08-at-5-44-17-PM.png",
    ],
    features: [
      "Global scholarship discovery with advanced filters",
      "Streamlined scholarship application process",
      "Real-time application tracking",
      "Secure online payment system",
      "Role-based user management (Student, Moderator, Admin)",
      "Reviews and ratings for scholarships and universities",
      "Analytics dashboard for insights and trends",
      "24/7 platform support",
    ],
    techStack: [
      "React",
      "Firebase",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Stripe",
      "JWT",
    ],
    tags: ["@react", "@fullstack", "@firebase"],
    links: {
      frontend: "https://github.com/Samin1362/ScholarStream-Client-Side.git",
      backend: "https://github.com/Samin1362/ScholarStream-Server-Side.git",
      live: "https://scholarstream-firebase-project.web.app",
    },
    credentials: {
      email: "admin@gmail.com",
      password: "1234Admin*",
      note: "Admin account for testing",
    },
    borderColor: "#0F766E",
    gradient: "linear-gradient(145deg, #0F766E, #22C55E, #16A34A)",
    displayOrder: 2,
    isVisible: true,
  },
  {
    id: 4,
    userId: null,
    title: "KrishiLink Agro Marketplace",
    subtitle: "Full Stack Project",
    type: "Full Stack",
    description:
      "KrishiLink is a modern digital agro-marketplace that connects farmers directly with buyers, eliminating middlemen and ensuring fair pricing. The platform allows farmers to post crops, buyers to show interest, and manages transactions through a secure, scalable backend API with real-time updates and role-based access.",
    images: [
      "https://i.postimg.cc/JnffXk5x/Screenshot-2026-02-08-at-5-57-15-PM.png",
    ],
    features: [
      "Direct farmer-to-buyer crop marketplace",
      "Crop posting with full CRUD operations",
      "Interest and inquiry management system",
      "Automatic quantity adjustment on deal acceptance",
      "Firebase JWT authentication & authorization",
      "Role-based access control",
      "Advanced crop search and filtering",
      "Responsive and mobile-first UI",
      "Production-ready RESTful API",
    ],
    techStack: [
      "React",
      "Vite",
      "Tailwind CSS",
      "Firebase Authentication",
      "Node.js",
      "Express.js",
      "MongoDB",
      "JWT",
      "Vercel",
    ],
    tags: ["@react", "@fullstack", "@firebase", "@mongodb"],
    links: {
      github:
        "https://github.com/Samin1362/PH-Assignment-10-KrishiLink-client-side.git",
      frontend: "https://krishilink-project-1452e.web.app",
      backend:
        "https://github.com/Samin1362/PH-Assignment-10-KrishiLink-server-side.git",
      live: "https://krishilink-project-1452e.web.app",
    },
    credentials: {
      email: "israk1991@gmail.com",
      password: "1234Israk*",
      note: "Admin account for testing",
    },
    borderColor: "#166534",
    gradient: "linear-gradient(145deg, #166534, #22C55E, #4ADE80)",
    displayOrder: 3,
    isVisible: true,
  },
  {
    id: 5,
    userId: null,
    title: "Game Hub for Gamers",
    subtitle: "Frontend Project",
    type: "React.js",
    description:
      "A modern gaming community platform built with React and Firebase. This game hub provides gamers with a centralized space to discover games, connect with other players, track achievements, and participate in gaming communities.",
    images: ["https://i.postimg.cc/Ss0tjyjb/temp-Imagevdm3v-F.avif"],
    features: [
      "Firebase authentication and authorization",
      "Real-time game library updates",
      "User profiles and achievements",
      "Gaming community forums",
      "Game reviews and ratings",
      "Social features and friend lists",
    ],
    techStack: ["React", "Firebase", "Firestore", "Firebase Auth", "Tailwind CSS"],
    tags: ["@firebase"],
    links: {
      frontend: "https://game-store-firebase-auth.web.app",
      live: "https://game-store-firebase-auth.web.app",
    },
    credentials: null,
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(145deg, #1E1B4B, #8B5CF6, #EC4899)",
    displayOrder: 4,
    isVisible: true,
  },
  {
    id: 10,
    userId: null,
    title: "Artwork Classification",
    subtitle: "Full Stack Project + AI",
    type: "AI/ML",
    description:
      "An intelligent artwork classification system powered by AI and blockchain technology. This platform uses machine learning algorithms to categorize and authenticate digital artworks, providing a secure and transparent marketplace for digital art.",
    images: ["https://i.postimg.cc/qv4p6q04/temp-Image-VQdn-IE.avif"],
    features: [
      "AI-powered artwork classification",
      "Blockchain-based authentication",
      "Secure digital marketplace",
      "Image recognition and analysis",
      "Artist portfolio management",
      "Real-time bidding system",
    ],
    techStack: [
      "React",
      "MongoDB",
      "Express.js",
      "Node.js",
      "TensorFlow",
      "Blockchain",
    ],
    tags: ["@react", "@mongodb", "@express", "@nodejs", "@blockchain"],
    links: {
      frontend: "https://merakinexus.netlify.app",
      live: "https://merakinexus.netlify.app",
    },
    credentials: {
      email: "demo@merakinexus.com",
      password: "Demo@2024",
      note: "Demo account — Limited permissions",
    },
    borderColor: "#7C3AED",
    gradient: "linear-gradient(145deg, #6D28D9, #1E1B4B)",
    displayOrder: 5,
    isVisible: true,
  },
  {
    id: 11,
    userId: null,
    title: "AI Assistant for Entrepreneurs",
    subtitle: "Machine Learning Project",
    type: "AI/ML",
    description:
      "An AI-powered virtual assistant designed to help entrepreneurs make data-driven business decisions. The platform leverages machine learning models to provide insights, recommendations, and automated support for various business operations.",
    images: ["https://i.postimg.cc/x8BcS2bV/temp-Imagev5-E4bh.avif"],
    features: [
      "Natural language processing for queries",
      "Business analytics and insights",
      "Automated report generation",
      "Market trend analysis",
      "Predictive analytics",
      "Personalized recommendations",
    ],
    techStack: ["React", "Python", "TensorFlow", "OpenAI API", "Node.js"],
    tags: ["@react"],
    links: {
      frontend: "https://silver-pixie-86b386.netlify.app",
      live: "https://silver-pixie-86b386.netlify.app",
    },
    credentials: null,
    borderColor: "#1E3A8A",
    gradient: "linear-gradient(145deg, #1E3A8A, #10B981, #0D9488)",
    displayOrder: 6,
    isVisible: true,
  },
  {
    id: 12,
    userId: null,
    title: "ItemHub E-commerce Application",
    subtitle: "Full Stack Application",
    type: "Next.js",
    description:
      "ItemHub is a modern e-commerce web application built with Next.js App Router. It features a public landing page, item browsing, detailed product views, authentication with cookie-based sessions, protected routes, and a secure item creation flow integrated with an Express backend API.",
    images: [
      "https://i.postimg.cc/TwbRBGkh/Screenshot-2026-02-08-at-6-12-17-PM.png",
    ],
    features: [
      "Modern landing page with 7+ informational sections",
      "Item listing and dynamic item details pages",
      "Authentication with HTTP-only cookie-based sessions",
      "Protected routes using Next.js middleware",
      "Add item functionality for authenticated users only",
      "Form validation using Zod and react-hook-form",
      "Toast notifications for user feedback",
      "Fully responsive UI with Tailwind CSS",
      "Environment-based API configuration",
    ],
    techStack: [
      "Next.js (App Router)",
      "React",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "JWT",
      "Axios",
      "Zod",
    ],
    tags: ["@nextjs", "@fullstack", "@auth"],
    links: {
      frontend: "https://github.com/Samin1362/SCIC_Assignment_9_Frontend.git",
      backend: "https://github.com/Samin1362/SCIC_Assignment_9_Backend.git",
      live: "https://scic-frontend-assignment-9.vercel.app",
    },
    credentials: null,
    borderColor: "#2563EB",
    gradient: "linear-gradient(145deg, #2563EB, #3B82F6, #60A5FA)",
    displayOrder: 7,
    isVisible: true,
  },
];

export function deriveProjectTypes(projects: Project[]): string[] {
  const set = new Set<string>();
  for (const p of projects) set.add(p.type);
  return ["All", ...Array.from(set)];
}
